"""Hardware interface consumed by the motion layer."""

from typing import Dict, Mapping, Optional, Protocol

from ..protocol.can_motor_arm_lib import JointConfig, JointFeedback


class ArmHardware(Protocol):
    name: str
    joints: Dict[str, JointConfig]
    connected: bool

    def connect(self) -> None: ...
    def close(self) -> None: ...
    def read_joint_angle(self, key: str) -> Optional[float]: ...
    def read_joint_feedback(self, key: str) -> JointFeedback: ...
    def read_joint_status(self, key: str) -> Optional[dict]: ...
    def read_motor_version(self, key: str) -> Optional[dict]: ...
    def read_motor_params(self, key: str) -> Optional[dict]: ...
    def read_motor_compact(self, key: str) -> Optional[dict]: ...
    def set_speed_limit(self, key: str, joint_rpm: float) -> bool: ...
    def set_accel_limit(self, key: str, joint_rpm_s: float) -> bool: ...
    def set_max_current(self, key: str, amp: float) -> bool: ...
    def set_current_slope(self, key: str, amp_per_sec: float) -> bool: ...
    def read_or_set_gain(
        self, key: str, gain: str, value: Optional[float]
    ) -> Optional[float]: ...
    def set_q_current(self, key: str, amp: float) -> Optional[float]: ...
    def set_speed_mode(self, key: str, joint_rpm: float) -> Optional[float]: ...
    def go_home_shortest(self, key: str) -> bool: ...
    def command_positions(self, targets: Mapping[str, float]) -> None: ...
    def clear_faults(self) -> Dict[str, bool]: ...
    def set_zero(self, key: str) -> bool: ...
    def set_brake(self, key: str, closed: bool) -> Optional[bool]: ...
    def read_brake(self, key: str) -> Optional[bool]: ...
    def disable_all(self) -> bool: ...
